### ISSUE TITLE
リファクタリング(ログインから完了まで)

### ISSUE THREAD

**Issue by hikarut** [egg-system/olive-front#16]
* エラーハンドリングする
* componentsの整理
* Vuexの使い方整理(mapState使うなど)

**Comment by nuno929** [comment]
- vuexの名前空間を使って、下記に整理する
　- 共通
　- 予約周り
　- ログイン周り
- componentsの整理は必要
　- atomic-designでいうところのorgnizerがない
- 上記、対応後にエラーハンドリングを詳細化する

**Comment by nuno929** [comment]
一次対応完了。
続く対応として、以下がある
https://github.com/egg-system/olive-front/pull/91#issuecomment-533787096

**Comment by nuno929** [comment]
対応完了したため、クローズ
