### ISSUE TITLE
店舗IDをgetパラメータにする

### ISSUE THREAD

**Issue by nuno929** [egg-system/olive-front#64]
# 対応内容
## 実装方針
- 下記の仕様のmiddlewareを実装する
　- getパラメータがない場合、店舗IDは1になる
　- 存在する場合は下記にセットする
　　- https://github.com/egg-system/olive-front/blob/develop/store/shop.js#L17
- 下記にmiddlewareをセットする
　- https://github.com/egg-system/olive-front/blob/develop/layouts/default.vue
## 参考
- 似たような処理をしているmiddleware
　- https://github.com/egg-system/olive-front/blob/develop/middleware/init-menu-index.js
- 下記のメソッドで店舗情報を取得する
　- https://github.com/egg-system/olive-front/blob/develop/store/shop.js#L30-L34

**Comment by mkato7914** [comment]
@nuno929 
すみません、そもそものお話で申し訳ないのですがこの対応の目的としては
多店舗対応用（https://trello.com/c/uQMj7VsM）で、このissueはその中の
- ログイン時に入力した店舗を保持するロジックの実装
のことでしょうか・・・？

>存在する場合は下記にセットする
の下記にセットというのは、
https://github.com/egg-system/olive-front/blob/develop/layouts/default.vue
をさすのでしょうか？

**Comment by nuno929** [comment]
@mkato7914 
これは全く別の対応になりますので、ご放念ください。
https://trello.com/c/uQMj7VsM

対応の目的としては、下記二つのパスで、表示されるメニューなどが可変になることが目的です。
- http://localhost:3000/menus?menuIndex=1
- http://localhost:3000/menus?menuIndex=1&shopId=3

> 存在する場合は下記にセットする
こちら、脱字になりますね...
下記のセッターで店舗オブジェクトの内容をセットすることを意味しております。
- https://github.com/egg-system/olive-front/blob/develop/store/shop.js#L17

`store.dispatch('shop/setShop', shopObject)` などで呼び出し可能です。
公式のドキュメントは下記になりますので、参考にしていただければと思います
https://vuex.vuejs.org/ja/guide/actions.html

**Comment by mkato7914** [comment]
ご回答ありがとうございます！

**Comment by nuno929** [comment]
対応済みなので、クローズ
